name: Renovate Dependency Updates

on:
  workflow_dispatch: # Permet de déclencher manuellement
  schedule:
    - cron: "0 2 * * *" # Exécution quotidienne à 2h du matin

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configuration de Renovate
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.0
        with:
          # Activer les logs avancés pour le débogage
          logLevel: debug
          args: --autodiscover
        env:
          # Nécessaire pour authentifier Renovate
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
