name: Renovate Dependency Updates

on:
  workflow_dispatch: # Permet de déclencher manuellement
  schedule:
    - cron: "0 2 * * *" # Exécution quotidienne à 2h du matin

permissions: read-all

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configuration de Renovate
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          args: --repositories=Frantche/coder-full
        env:
          # Nécessaire pour authentifier Renovate
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
