name: Renovate Dependency Updates

on:
  workflow_dispatch: # Permet de déclencher manuellement
  schedule:
    - cron: "0 2 * * *" # Exécution quotidienne à 2h du matin

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
